2024-01-12 10:08:34.305 - ETL_FT_SD_TO_XSIFF_20231228 [ERROR   ] [Serial no.]列只有数字
2024-01-12 10:08:34.523 - __init__   [ERROR   ] File:QG35-CW_GD400TAS100L6S_只有数字.xlsx Move To Error Folder
                                                Error: None
2024-01-12 10:08:35.146 - ETL_FT_SD_TO_XSIFF_20231228 [ERROR   ] 有非数值型的数据，例如当前遇到的第一个为PASS
2024-01-12 10:08:35.279 - __init__   [ERROR   ] File:XLECHQ122-CW-FC_新阳光-GD200FYS100L6S-CW_多列测试.xlsx Move To Error Folder
                                                Error: None
2024-01-12 10:08:35.696 - ETL_FT_SD_TO_XSIFF_20231228 [ERROR   ] [Serial no.]列无法正确取值，例如遇到的第一个错误值为：80 D12740100000
2024-01-12 10:08:35.890 - __init__   [ERROR   ] File:XLECHQ217-CW-FC_新阳光GD200FYS100L6S-CW.xlsx Move To Error Folder
                                                Error: None
2024-01-12 10:08:40.818 - ETL_FT_SD_TO_XSIFF_20231228 [ERROR   ] [Serial no.]列无法正确取值，例如遇到的第一个错误值为：200041 D12740000000
2024-01-12 10:08:41.022 - __init__   [ERROR   ] File:XWECYQH20-CW_GD600MLS100L6S_取不到header数据.xlsx Move To Error Folder
                                                Error: None
2024-01-12 10:08:41.821 - ETL_FT_SD_TO_XSIFF_20231228 [ERROR   ] 有非数值型的数据，例如当前遇到的第一个为∞
2024-01-12 10:08:42.062 - __init__   [ERROR   ] File:XWECYQH62-GW_GD600MLS100L6S-GW.xlsx Move To Error Folder
                                                Error: None
2024-01-12 10:08:42.947 - ETL_FT_SD_TO_XSIFF_20231228 [ERROR   ] 有非数值型的数据，例如当前遇到的第一个为预测试
2024-01-12 10:08:43.122 - __init__   [ERROR   ] File:XWECZS889-GW_新阳光GD600MLS100L6S-GW_特殊字符测试.xlsx Move To Error Folder
                                                Error: None
2024-01-12 11:04:33.919 - ETL_FT_SD_TO_XSIFF_20231228 [ERROR   ] [Serial no.]列只有数字
2024-01-12 11:04:34.063 - __init__   [ERROR   ] File:QG35-CW_GD400TAS100L6S_只有数字.xlsx Move To Error Folder
                                                Error: None
2024-01-12 11:04:34.320 - ETL_FT_SD_TO_XSIFF_20231228 [ERROR   ] can only concatenate str (not "int") to str
Traceback (most recent call last):
  File "D:/Ina/ETL_XdmLib_2.A.13/ETL_XdmLib_2.A.13/EDAETL/ETL_TABLE/ETL_FT_SD_TO_XSIFF/ETL_FT_SD_TO_XSIFF_20231228.py", line 332, in do_file
    parameter = column_parameter.upper() + '_'+column_parameter_value+'_' + second_row_value.split('(')[-1].split(')')[0]+'_'+column.split('[')[0]
TypeError: can only concatenate str (not "int") to str
Stack (most recent call last):
  File "D:/Ina/ETL_XdmLib_2.A.13/ETL_XdmLib_2.A.13/EDAETL/ETL_TABLE/ETL_FT_SD_TO_XSIFF/ETL_FT_SD_TO_XSIFF_20231228.py", line 567, in <module>
    skip_file, None, log, config, config_sql)
  File "../..\XdmLib\CustomFuction.py", line 597, in file2db_init
    file, pre_params, db_src, db_tgt)
  File "D:/Ina/ETL_XdmLib_2.A.13/ETL_XdmLib_2.A.13/EDAETL/ETL_TABLE/ETL_FT_SD_TO_XSIFF/ETL_FT_SD_TO_XSIFF_20231228.py", line 382, in do_file
    log.error(ex, exc_info=True, stack_info=True)
2024-01-12 11:04:34.493 - __init__   [ERROR   ] File:TLECGQG81-CW_阳光GD200FYS100L6S_取不到header数据..xlsx Move To Error Folder
                                                Error: None
2024-01-12 11:04:34.696 - ETL_FT_SD_TO_XSIFF_20231228 [ERROR   ] can only concatenate str (not "int") to str
Traceback (most recent call last):
  File "D:/Ina/ETL_XdmLib_2.A.13/ETL_XdmLib_2.A.13/EDAETL/ETL_TABLE/ETL_FT_SD_TO_XSIFF/ETL_FT_SD_TO_XSIFF_20231228.py", line 332, in do_file
    parameter = column_parameter.upper() + '_'+column_parameter_value+'_' + second_row_value.split('(')[-1].split(')')[0]+'_'+column.split('[')[0]
TypeError: can only concatenate str (not "int") to str
Stack (most recent call last):
  File "D:/Ina/ETL_XdmLib_2.A.13/ETL_XdmLib_2.A.13/EDAETL/ETL_TABLE/ETL_FT_SD_TO_XSIFF/ETL_FT_SD_TO_XSIFF_20231228.py", line 567, in <module>
    skip_file, None, log, config, config_sql)
  File "../..\XdmLib\CustomFuction.py", line 597, in file2db_init
    file, pre_params, db_src, db_tgt)
  File "D:/Ina/ETL_XdmLib_2.A.13/ETL_XdmLib_2.A.13/EDAETL/ETL_TABLE/ETL_FT_SD_TO_XSIFF/ETL_FT_SD_TO_XSIFF_20231228.py", line 382, in do_file
    log.error(ex, exc_info=True, stack_info=True)
2024-01-12 11:04:34.876 - __init__   [ERROR   ] File:XLECHQ122-CW-FC_新阳光-GD200FYS100L6S-CW_多列测试.xlsx Move To Error Folder
                                                Error: None
2024-01-12 11:04:35.269 - ETL_FT_SD_TO_XSIFF_20231228 [ERROR   ] [Serial no.]列无法正确取值，例如遇到的第一个错误值为：80 D12740100000
2024-01-12 11:04:35.423 - __init__   [ERROR   ] File:XLECHQ217-CW-FC_新阳光GD200FYS100L6S-CW.xlsx Move To Error Folder
                                                Error: None
2024-01-12 11:04:39.104 - ETL_FT_SD_TO_XSIFF_20231228 [ERROR   ] can only concatenate str (not "int") to str
Traceback (most recent call last):
  File "D:/Ina/ETL_XdmLib_2.A.13/ETL_XdmLib_2.A.13/EDAETL/ETL_TABLE/ETL_FT_SD_TO_XSIFF/ETL_FT_SD_TO_XSIFF_20231228.py", line 332, in do_file
    parameter = column_parameter.upper() + '_'+column_parameter_value+'_' + second_row_value.split('(')[-1].split(')')[0]+'_'+column.split('[')[0]
TypeError: can only concatenate str (not "int") to str
Stack (most recent call last):
  File "D:/Ina/ETL_XdmLib_2.A.13/ETL_XdmLib_2.A.13/EDAETL/ETL_TABLE/ETL_FT_SD_TO_XSIFF/ETL_FT_SD_TO_XSIFF_20231228.py", line 567, in <module>
    skip_file, None, log, config, config_sql)
  File "../..\XdmLib\CustomFuction.py", line 597, in file2db_init
    file, pre_params, db_src, db_tgt)
  File "D:/Ina/ETL_XdmLib_2.A.13/ETL_XdmLib_2.A.13/EDAETL/ETL_TABLE/ETL_FT_SD_TO_XSIFF/ETL_FT_SD_TO_XSIFF_20231228.py", line 382, in do_file
    log.error(ex, exc_info=True, stack_info=True)
2024-01-12 11:04:39.936 - __init__   [ERROR   ] File:XWECIQ743-CW_新阳光GD600MLS100L6S-CW-D125486-左.xlsx Move To Error Folder
                                                Error: None
2024-01-12 11:04:40.872 - ETL_FT_SD_TO_XSIFF_20231228 [ERROR   ] [Serial no.]列无法正确取值，例如遇到的第一个错误值为：200041 D12740000000
2024-01-12 11:04:40.992 - __init__   [ERROR   ] File:XWECYQH20-CW_GD600MLS100L6S_取不到header数据.xlsx Move To Error Folder
                                                Error: None
2024-01-12 11:04:41.847 - ETL_FT_SD_TO_XSIFF_20231228 [ERROR   ] can only concatenate str (not "int") to str
Traceback (most recent call last):
  File "D:/Ina/ETL_XdmLib_2.A.13/ETL_XdmLib_2.A.13/EDAETL/ETL_TABLE/ETL_FT_SD_TO_XSIFF/ETL_FT_SD_TO_XSIFF_20231228.py", line 332, in do_file
    parameter = column_parameter.upper() + '_'+column_parameter_value+'_' + second_row_value.split('(')[-1].split(')')[0]+'_'+column.split('[')[0]
TypeError: can only concatenate str (not "int") to str
Stack (most recent call last):
  File "D:/Ina/ETL_XdmLib_2.A.13/ETL_XdmLib_2.A.13/EDAETL/ETL_TABLE/ETL_FT_SD_TO_XSIFF/ETL_FT_SD_TO_XSIFF_20231228.py", line 567, in <module>
    skip_file, None, log, config, config_sql)
  File "../..\XdmLib\CustomFuction.py", line 597, in file2db_init
    file, pre_params, db_src, db_tgt)
  File "D:/Ina/ETL_XdmLib_2.A.13/ETL_XdmLib_2.A.13/EDAETL/ETL_TABLE/ETL_FT_SD_TO_XSIFF/ETL_FT_SD_TO_XSIFF_20231228.py", line 382, in do_file
    log.error(ex, exc_info=True, stack_info=True)
2024-01-12 11:04:41.992 - __init__   [ERROR   ] File:XWECYQH62-GW_GD600MLS100L6S-GW.xlsx Move To Error Folder
                                                Error: None
2024-01-12 11:04:42.862 - ETL_FT_SD_TO_XSIFF_20231228 [ERROR   ] can only concatenate str (not "int") to str
Traceback (most recent call last):
  File "D:/Ina/ETL_XdmLib_2.A.13/ETL_XdmLib_2.A.13/EDAETL/ETL_TABLE/ETL_FT_SD_TO_XSIFF/ETL_FT_SD_TO_XSIFF_20231228.py", line 332, in do_file
    parameter = column_parameter.upper() + '_'+column_parameter_value+'_' + second_row_value.split('(')[-1].split(')')[0]+'_'+column.split('[')[0]
TypeError: can only concatenate str (not "int") to str
Stack (most recent call last):
  File "D:/Ina/ETL_XdmLib_2.A.13/ETL_XdmLib_2.A.13/EDAETL/ETL_TABLE/ETL_FT_SD_TO_XSIFF/ETL_FT_SD_TO_XSIFF_20231228.py", line 567, in <module>
    skip_file, None, log, config, config_sql)
  File "../..\XdmLib\CustomFuction.py", line 597, in file2db_init
    file, pre_params, db_src, db_tgt)
  File "D:/Ina/ETL_XdmLib_2.A.13/ETL_XdmLib_2.A.13/EDAETL/ETL_TABLE/ETL_FT_SD_TO_XSIFF/ETL_FT_SD_TO_XSIFF_20231228.py", line 382, in do_file
    log.error(ex, exc_info=True, stack_info=True)
2024-01-12 11:04:43.084 - __init__   [ERROR   ] File:XWECZS889-GW_新阳光GD600MLS100L6S-GW_特殊字符测试.xlsx Move To Error Folder
                                                Error: None
2024-01-12 11:05:37.139 - ETL_FT_SD_TO_XSIFF_20231228 [ERROR   ] [Serial no.]列只有数字
2024-01-12 11:05:37.411 - __init__   [ERROR   ] File:QG35-CW_GD400TAS100L6S_只有数字.xlsx Move To Error Folder
                                                Error: None
2024-01-12 11:06:33.900 - ETL_FT_SD_TO_XSIFF_20231228 [ERROR   ] [Serial no.]列只有数字
2024-01-12 11:06:34.176 - __init__   [ERROR   ] File:QG35-CW_GD400TAS100L6S_只有数字.xlsx Move To Error Folder
                                                Error: None
2024-01-12 11:07:49.476 - ETL_FT_SD_TO_XSIFF_20231228 [ERROR   ] [Serial no.]列只有数字
2024-01-12 11:07:49.701 - __init__   [ERROR   ] File:QG35-CW_GD400TAS100L6S_只有数字.xlsx Move To Error Folder
                                                Error: None
2024-01-12 11:08:04.748 - ETL_FT_SD_TO_XSIFF_20231228 [ERROR   ] [Serial no.]列只有数字
2024-01-12 11:08:04.940 - __init__   [ERROR   ] File:QG35-CW_GD400TAS100L6S_只有数字.xlsx Move To Error Folder
                                                Error: None
2024-01-12 11:08:05.577 - ETL_FT_SD_TO_XSIFF_20231228 [ERROR   ] 有非数值型的数据，例如当前遇到的第一个为PASS
2024-01-12 11:08:05.726 - __init__   [ERROR   ] File:XLECHQ122-CW-FC_新阳光-GD200FYS100L6S-CW_多列测试.xlsx Move To Error Folder
                                                Error: None
2024-01-12 11:08:06.151 - ETL_FT_SD_TO_XSIFF_20231228 [ERROR   ] [Serial no.]列无法正确取值，例如遇到的第一个错误值为：80 D12740100000
2024-01-12 11:08:06.313 - __init__   [ERROR   ] File:XLECHQ217-CW-FC_新阳光GD200FYS100L6S-CW.xlsx Move To Error Folder
                                                Error: None
2024-01-12 11:08:11.350 - ETL_FT_SD_TO_XSIFF_20231228 [ERROR   ] [Serial no.]列无法正确取值，例如遇到的第一个错误值为：200041 D12740000000
2024-01-12 11:08:11.506 - __init__   [ERROR   ] File:XWECYQH20-CW_GD600MLS100L6S_取不到header数据.xlsx Move To Error Folder
                                                Error: None
2024-01-12 11:08:12.237 - ETL_FT_SD_TO_XSIFF_20231228 [ERROR   ] 有非数值型的数据，例如当前遇到的第一个为∞
2024-01-12 11:08:12.445 - __init__   [ERROR   ] File:XWECYQH62-GW_GD600MLS100L6S-GW.xlsx Move To Error Folder
                                                Error: None
2024-01-12 11:08:13.264 - ETL_FT_SD_TO_XSIFF_20231228 [ERROR   ] 有非数值型的数据，例如当前遇到的第一个为预测试
2024-01-12 11:08:13.476 - __init__   [ERROR   ] File:XWECZS889-GW_新阳光GD600MLS100L6S-GW_特殊字符测试.xlsx Move To Error Folder
                                                Error: None
